### ISSUE TITLE
reproduce the result of table 2 "source similarity"

### ISSUE THREAD

**Issue by wangqi1996** [jcyk/copyisallyouneed#1]
It's a really good job!
Could you provide the scripts or README.md to reproduce the result of table 2 "source similarity"?
thx.

**Comment by jcyk** [comment]
it based on BM25 and edit distance. Will add more info soon.

**Comment by jcyk** [comment]
Hi @wangqi1996 

pls check [bm25.py](https://github.com/jcyk/copyisallyouneed/blob/master/bm25.py) for details.
