### ISSUE TITLE
bleu score while training

### ISSUE THREAD

**Issue by yangkent114** [jcyk/copyisallyouneed#16]
Hello, while using the fifth script for training, I noticed a strange phenomenon during the training process. Before I reached step 8999, the bleu value in the validation set test was only about 1. However, by step 8999, the bleu value skyrocketed to 37，
![aa844027fefd4c2fcc0e478d71e0722](https://github.com/jcyk/copyisallyouneed/assets/155701145/e2ad3129-5d34-462f-9c8e-b1b1f8bd9368)
![bbb](https://github.com/jcyk/copyisallyouneed/assets/155701145/fa4c8558-c979-41be-a413-c7e5cbff1e88)
May I ask what caused this situation? If you could reply to me, I would greatly appreciate it

**Comment by yangkent114** [comment]
![Uploading aaa.png…]()

**Comment by rangehow** [comment]
这个问题可以看这个仓库里的 #6 issues，主要原因是在一定步数之前，验证过程只允许生成少量的输出。

**Comment by yangkent114** [comment]
> 这个问题可以看这个仓库里的 #6 issues，主要原因是在一定步数之前，验证过程只允许生成少量的输出。

非常感谢您的解答！！
