### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by Hannibal046** [jcyk/copyisallyouneed#3]
Hello,
thanks for your work. Do you have a plan to release the dataset you use or the preprocess function including bpe ? Since you aligned your dataset setting to [Gu et al. (2018)](https://arxiv.org/pdf/1705.07267.pdf)
Thanks very much

**Comment by jcyk** [comment]
Hi thanks for you interest. We plan to release related materials before this ACL.

**Comment by jcyk** [comment]
released. see readme
