### ISSUE TITLE
对于shell文件里的一些参数的疑惑和python文件中疑似有一个错处

### ISSUE THREAD

**Issue by 20184365** [jcyk/copyisallyouneed#4]
As a adventurer, I am working to reproduce your results(even it's a bit hard). I face two difficulties which stop me from continuing as below.

> 在scripts\build_index.sh中的cands.txt和scripts\wmt14\build_index.sh中的fullsearch.tgt.txt是什么？

> 另外在` retriever.py 中  ，下面这一段里的get_features的vocab没有实参，报错了

![image](https://user-images.githubusercontent.com/43506763/126609161-0ba683f2-3da7-4d94-9fc9-cf07f8267249.png)

I hope to hear from you.Good luck with your life and work.

**Comment by zotown** [comment]
你好，我遇到了同样的问题，不知道你当时是怎么解决的？

**Comment by rangehow** [comment]
没事，不用管，这儿没用上
