### ISSUE TITLE
Transformer BaseModel Bleu Score

### ISSUE THREAD

**Issue by Hannibal046** [jcyk/copyisallyouneed#6]
Hello. After running `scripts/train.vanilla.sh`,I got the following results in test set, taking the highest score.
|Bleu|ende |deen|enes|esen|
| ---- | ---- | ----  | ----  | ----|
|reported|54.90|60.76|61.54|64.07|
|My|52.50 | 58.26| 59.55|62.11|

On average, every bleu is  2 points lower than reported. I don't know what to do to make it better , could you please help me out?
Btw, I find a interesting thing when training in all four experiments: the dev bleu and test bleu remain almost zero utils some point it has a huge improvement while `acc` and `loss` did not change much 
![image](https://user-images.githubusercontent.com/38466901/128464029-f272dcd6-e1ba-49d1-9acb-463ba1dde2c0.png)

**Comment by Hannibal046** [comment]
I also made a little change in `transformer.py`,because the previous in-place operation will cause back prop problem.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/38466901/128464380-35c651d0-4a1e-40f4-b36c-488f1ae79bd2.png">

**Comment by jcyk** [comment]
Hi @Hannibal046. The sudden change is due to this line https://github.com/jcyk/copyisallyouneed/blob/76203350d1ac2716079ceaa0870a2d473d71c534/train.py#L175

**Comment by jcyk** [comment]
For the final results, I will have a try and let you know soon

**Comment by jcyk** [comment]
thx

**Comment by Hannibal046** [comment]
Thanks so much, it is really nice of you

**Comment by jcyk** [comment]
@Hannibal046 I took a try myself and obtained close results to those reported in our paper.
Pls make sure you follow the right steps in producing our results. (repo updated)
