### ISSUE TITLE
could you please share  the code file of bpe?

### ISSUE THREAD

**Issue by Hannibal046** [jcyk/copyisallyouneed#8]
Hello @jcyk 
I am wondering would you please share the code file of the bpe? since I want to encode a raw sentence into the same bpe encoding of the processed JRC corpus, thanks so much!

**Comment by jcyk** [comment]
Hi @Hannibal046  sorry but i don't have such bpe files. I got preprocessed data from the authors.
I am also interested in the code file. pls kindly let me know if you find a solution.
